application:
  description: Dating app for Cukurova University
  version: 1.0.0
  title: Dating app
  access_token_key: supersecretaccesstokenkey
  refresh_token_key: supersecretrefreshtokenkey
  issuer: Taylan
  access_token_expiration: 10



spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    javax:
      persistence:
        validation:
          mode: none
  datasource:
    url: jdbc:postgresql://localhost:5432/cunder_db
    username: postgres
    password: 1283